### ISSUE TITLE
Space in slug

### ISSUE THREAD

**Issue by AndrewBelt** [ValleyAudio/ValleyRackFree#11]
Because of how the new Plugin Manager, build system, plugin loader, and vcvrack.com API work, you'll unfortunately have to remove the space by the 0.6 release.
Best to make a 0.5.* update right before the 0.6 release and make a Facebook post telling people what to replace in their patch files.

**Comment by ValleyAudio** [comment]
I knew this day had come eventually. I'm writing a guide that I will include in the release. Hopefully people will read it since I've met users who don't use Facebook!

**Comment by ValleyAudio** [comment]
I will have this ready today.
