### ISSUE TITLE
Lingering Algorithm Artifacts

### ISSUE THREAD

**Issue by jonheal** [ValleyAudio/ValleyRackFree#12]
As you switch Dexter algorithms, small bits of the previous algorithm setting seem to assert themselves and play for a moment.

**Comment by ValleyAudio** [comment]
How do you mean? Do you have an example?

**Comment by jonheal** [comment]
I will see if I can record a sample.

--
Jon Heal
http://www.theheals.org/
Have a nice day!

**Comment by jonheal** [comment]
Maybe to describe it more accurately, it seems to take about a second for each algorithm to "settle in." It is most noticeable with operators in the chain that have the most effect on the signal. Is this "settling in time" normal? I recorded a sample here: (https://1drv.ms/u/s!Asy9MQ3kIBNQgbdzw0qQbTZ7_2HBRQ)

As I switch algorithms, after about a second, the sound changes. This is just a random Dexter patch: [](https://1drv.ms/u/s!Asy9MQ3kIBNQgbd0JvxItUssi6PEJA)

**Comment by jonheal** [comment]
Disregard! I forgot I had a delay it the path. User error!
Except the burp is still there, which you can here at the end of the audio file.

**Comment by ValleyAudio** [comment]
I think the burp is intermittent and is more to do with how Rack works.

 Dexter is a big module in terms of RAM usage as all the wave tables are loaded all at once. When Rack is closed I think you're hearing whatever is left in the audio buffer for a bit whilst Dexter is unloaded. So I don't think it's something I could solve unless there's a way of muting audio outputs as Rack closes.

**Comment by jonheal** [comment]
OK, thanks.

That is maybe a good thing for Andrew and crew to implement.
