### ISSUE TITLE
Topograph does not save the run state.

### ISSUE THREAD

**Issue by Euphorbium** [ValleyAudio/ValleyRackFree#14]
I got some old version, I see that features have changed, but if this has not been addressed, it might still be relevant. If you save a patch with topograph running, it loads with it off.

**Comment by ValleyAudio** [comment]
This is the same in the new version. The motivation was that it would wait for the user to be ready to begin the playback manually upon start up of Rack, much like a DAW like Logic. Would you prefer the running to state to be saved with the patch?

**Comment by Euphorbium** [comment]
I think that saving the state is better, this allows a choice. If you want
to have it off, you can save it as off, but if you want it on, you can't
save it as on.

**Comment by darloth** [comment]
Most(I think?) other modules preserve their running / paused state when you save/load a patch.

Personally, I also want to tell my patches when or if to start, but I would suggest that consistency is probably more valuable and expected here than convenience.

**Comment by ValleyAudio** [comment]
I will be updating it to save, just taking a short break from programming Rack at the moment, but it'll be early in the coming week you'll see this fixed.

**Comment by ValleyAudio** [comment]
@darloth Okay, it was simpler than I realised to add. This issue is now fixed.
