### ISSUE TITLE
muGraph skin messed up in Light mode

### ISSUE THREAD

**Issue by darloth** [ValleyAudio/ValleyRackFree#15]
![image](https://user-images.githubusercontent.com/8480048/38178239-4f854876-3606-11e8-859c-5a411d1210cf.png)

The dark mode looks fine, but the light mode looks like the above attachment.

Version 6.0, windows if that matters.

**Comment by darloth** [comment]
Though I will say - the dark skin doesn't look like the image you have posted here.  It lacks the Patt. Mode and Clock Res fields.  I'm quite certain I have the latest release binaries as of 30-03-2018, but less certain as to whether that matters or not.  Thought it worth mentioning.

**Comment by ValleyAudio** [comment]
@darloth I'm aware of it. The plugin manager version hasn't been updated yet, download the release copy in the releases section.

**Comment by darloth** [comment]
Thanks - honestly thought I -had- downloaded that one, but clearly not!

**Comment by ValleyAudio** [comment]
This plugin manager thing right now feels all screwed up for me haha, I hope my Github release works well for you anyway.
