### ISSUE TITLE
Link to Dexter quickstart guide on front page does not work

### ISSUE THREAD

**Issue by darloth** [ValleyAudio/ValleyRackFree#16]
On https://github.com/ValleyAudio/ValleyRackFree there is the sentence
`In brief, Dexter is an FM wavetable oscillator. See the Dexter Quick Start guide pdf for more information available here` where 'here' is a link.

The link resolves to https://github.com/ValleyAudio/ValleyRackFree/releases/download/0.6.0/DexterQuickStart.pdf , but following that link results in a github 404 page.

**Comment by ValleyAudio** [comment]
Fixed
