### ISSUE TITLE
Plateau Module

### ISSUE THREAD

**Issue by blackearth2014** [ValleyAudio/ValleyRackFree#18]
The plate reverb on this module is crazy good. Good Work!

**Comment by martin-lueders** [comment]
Is it just me, or does the DRY not work for the right channel?

besides that, I agree that Plateau is just a great module! Superb sound and great possibilities. Congratulations!

**Comment by ValleyAudio** [comment]
This is known and fixed in code. I suspect the build team have overlooked my request.

**Comment by martin-lueders** [comment]
Thanks. Update is life now.
