### ISSUE TITLE
Please undo what you did to Plateau with update 0.6.7

### ISSUE THREAD

**Issue by Petervos2018** [ValleyAudio/ValleyRackFree#23]
I just spend 3 hours listening to a Omri Cohen patch that sounded nothing like his video on youtube.
This one : https://www.youtube.com/watch?v=wptK0AUrf8A
And here is the patch : https://patchstorage.com/wp-content/uploads/2019/01/Storm-final-patch.vcv
The reason was that I just updated the plug ins and was using Plateau 6.7.0 .
It sounds horrible , I mean very different than the previous version.
After going back to version 6.6.0 all was well again.
I don't know what you did but please undo this.

Thanks for all your great plugins,

Greetings Peter.

**Comment by ValleyAudio** [comment]
Hi Peter,

I corrected a couple of bugs which should not have altered the audio quality, other than correcting how the "Input Diffuse" bypass switch worked, plus normalising the left an right inputs to each other if only one input is corrected.

I tested Omri's patch and it seems to sound similar to his audio. Could you send me an audio clip of what you are hearing in your patch?

Best regards,
Dale

**Comment by ValleyAudio** [comment]
@Petervos2018  Actually Peter this is my bad. I accidentally made the Dry signal x10 quieter. You can make the 0.6.6 version sound like 0.6.7 by turning down the Dry knob. 

I've issued a 0.6.8 update to the plugin manager which will be there very soon. Sorry about this! I'm glad you spotted it :D

**Comment by Petervos2018** [comment]
I'm glad you found it/something because I would not be able to tell you what was different, I would say it sounded "Less Crispy" and that would be all you had to work with.
Happily waiting for the update,

Greetings Peter.

**Comment by ValleyAudio** [comment]
@Petervos2018 Yeah, "Less crispy" is a good description.

Thanks! Dale
