### ISSUE TITLE
Plateau wet panning bug

### ISSUE THREAD

**Issue by wiqid** [ValleyAudio/ValleyRackFree#25]
In version 0.6.9 (not tested others), the wet signal has significant panning, depending on the size and delay settings. Video showing the problem: https://youtu.be/z8tsmklCoWs

**Comment by ValleyAudio** [comment]
This is not an issue, yet a characteristic of algorithmic reverbs. https://community.vcvrack.com/t/valley-plateau-balance-issues/1349/6?u=valley.audio
