### ISSUE TITLE
Plateau has gain backward with the Dattorro paper 

### ISSUE THREAD

**Issue by raphaelmor** [ValleyAudio/ValleyRackFree#26]
This might be inconsequential (as Plateau sounds incredibly good as is).
The gain of the AllPass Filters seems backward from the Dattorro paper.

For example, the paper describes it's input diffusion filters like this : 
![screenshot 2019-01-22 at 17 23 28](https://user-images.githubusercontent.com/772779/51549345-877d1900-1e6a-11e9-8173-5b2d5e66f580.png)

And the AllPassFilter implements it like this: 
```
_inSum = input + delay.output * gain;
output = delay.output + _inSum * gain * -1;
```
with a positive gain : 
```
_inApf1 = AllpassFilter<double>(dattorroScale(20 * _kInApf1Time), dattorroScale(_kInApf1Time), inputDiffusion1); // 0.75
```

It seems that to match the paper, the signs of the diffusion gains (both inputDiffusion* and plateDiffusion*) in the `Dattorro` constructor should be inverted.

I'm just learning about reverb algorithms so I might have missed something and this might be intentional.

**Comment by ValleyAudio** [comment]
Besides, I did some testing and with the original method it sound slightly more "ringy" to my ears in the input section, but the impulse response of the entire reverb sounds pretty much the same.

**Comment by raphaelmor** [comment]
No problem, I was just curious to know if this was intentional or an oversight as I'm just beginning to learn about DSP/Reverb algorithms.
Maybe a github issue was not the right medium :) sorry about that !

**Comment by ValleyAudio** [comment]
@raphaelmor Haha it's fine, it's one way of contacting me. I can point you towards some nice material about reverb algorithms and stuff.

Have you checkout the Valhalla DSP blog?
