### ISSUE TITLE
Interzone - Fine Issue

### ISSUE THREAD

**Issue by n6smith** [ValleyAudio/ValleyRackFree#27]
Love the new Interzone module... However, the Fine tune knob doesn't appear to be functional.  Coarse works ok but Fine does nothing to the tuning that i can discern...

Cheers!

**Comment by ValleyAudio** [comment]
Oh dear, looks like over looked that param by accident. I'll fix it when I get home :D

**Comment by n6smith** [comment]
No worries :)

Nigel (The Art Of Sound)
