### ISSUE TITLE
Interzone Env polarity, three stages ?

### ISSUE THREAD

**Issue by Petervos2018** [ValleyAudio/ValleyRackFree#28]
it goes from +1 to -1 to zero? and then back to +1 ...
Is this intended ?

Greetings Peter

**Comment by ValleyAudio** [comment]
Huh, no this is also another bug. Didn't anticipate how the switches operate in Rack.

**Comment by Petervos2018** [comment]
And it's fixed already , Wow Dale you're fast, 
Love this new one and the old stuff as well.

Thanks Peter.
