### ISSUE TITLE
Interzone sound stopped

### ISSUE THREAD

**Issue by infamedavid** [ValleyAudio/ValleyRackFree#31]
I have Interzone a patch and I loaded XFXwave in the patch and play with the modulations of the XFX wave and eventually the mS is down, when it happened Interzone send a hi peak signal, it frosed  and stop to produce  sounds, restarting the vcv rack  fix the issue

(the other modules in the patch  continue to work perfectly )

the OS is linux 64 bits

![screenshot_20190226_230707](https://user-images.githubusercontent.com/22543817/53468266-10036080-3a8c-11e9-8b19-415e3f005898.png)

**Comment by ValleyAudio** [comment]
So this problem only happened once?

**Comment by infamedavid** [comment]
yes, it happened   when the XFXwave make down the mS bar, yes here is the patch  it have semiramis, hora drumkits, pcm drums and pulse matrix
[041_XFX.vcv.zip](https://github.com/ValleyAudio/ValleyRackFree/files/2919832/041_XFX.vcv.zip)
