### ISSUE TITLE
Plateau: Output goes absurdly high 

### ISSUE THREAD

**Issue by patman023** [ValleyAudio/ValleyRackFree#32]
It's like there's no clipping diodes O_o ... I don't think I should be getting >60Vpp on output for really any reason, especially when I have the Wet output at ~10:00 and Dry turned off.

![plateauly-shnikes](https://user-images.githubusercontent.com/36520477/53599253-fdf4f100-3b63-11e9-9645-b673000b6cd2.png)

Is there any way to add a context menu item for either output saturation, or gain staging, or... something?

Cheers,
P

https://vcvrack.com/manual/VoltageStandards.html#output-saturation

**Comment by ValleyAudio** [comment]
Hmmm. Okay, thats actually a good idea! 

Alright, I expected loud output if you have decay moderately high as the input will just be accumulated to the existing reverb, and retrospect I should have added input gain knobs, but there's like no room left on the panel.

However, my solution is to add your idea of soft saturation as well as an input sensitivity option in the menu e.g either 0 or - 18db pad. Sound good?

**Comment by patman023** [comment]
Sounds great! Or rather, it will!
