### ISSUE TITLE
Interzone: Trigger input doesn't work

### ISSUE THREAD

**Issue by rubyglow** [ValleyAudio/ValleyRackFree#33]
OS version: MacOS 10.12.6 (Sierra)
Valley plugin version: 0.6.16 (at the time of writing this is the latest from plugin manager)

The "Trig" (trigger) input in the Env block of Interzone does not seem to work. I would expect a trigger pulse on the trigger input to trigger the envelope, but instead nothing happens. The "Gate" input works fine and as expected.

I have made a video that shows the bug: https://www.youtube.com/watch?v=npIpk8cGX7w

I'll go through what I show in the video:

- At first the clock is stopped, and I press the "Man" button twice, to manually trigger the envelope, to demonstrate what sound is expected from this envelope at full duty-cycle.

- Then I start the clock, and the gate goes to the "Gate" input of Interzone, using 4 different duty-cycles, from max. width down to trigger, to demonstrate that the Gate input and envelope works as expected.

- The thing to also notice is, that for each gate happening, the LED light of the "Man" button switches on.

- Then still with the clock running I change the cable, so that the gate input goes to the "Trig" input instead. I step through all 4 duty-cycles again, to demonstrate that none of them activates the envelope through the Trig input.

- The very interesting thing to also notice here is, that for each trigger input happening, the LED light of the "Man" button never switches on.

- Finally, with the clock still running, and the input still to "Trig", I press and hold the "Man" button twice, to demonstrate the curious fact, that when doing that the trigger input actually works as expected. To me that would seem to hold a big clue to what inside the module is not quite wired up correctly.

It would be really useful if the trigger input also worked.

PS: Otherwise I love the Interzone module. It's a very nice module, that sounds good, with a very well chosen feature set. Well done!

**Comment by ValleyAudio** [comment]
@rubyglow It's not so much a bug but perhaps a less than optimal implementation on my behalf. The trigger in this case should have been called "re-trigger" since it re-triggers the envelope whilst the gate is high. That's why the Man(ual) LED flashes when triggers are detected, merely as an indication that it received it.

Having said that, I can see why an "Attack-Decay" trigger would be useful, and implementing it would not alter the behaviour of Interzone since I can retain the "re-trigger" behaviour :

**Comment by rubyglow** [comment]
Ahh! I see. Yeah, implementing the dual-behaviour you mention would be great. It would be re-trigger with the gate patched, and without the gate patched it would trigger an AD envelope. That would be very usefu! Thanks Dale!
