### ISSUE TITLE
dexter wavetables for other vst synths.

### ISSUE THREAD

**Issue by DarkFifiLaFume** [ValleyAudio/ValleyRackFree#35]
Hi!

I was wondering if you still have the wavetables in wav format so I could use them in Icarus/Rapid. 
Thanks.

**Comment by ValleyAudio** [comment]
Hi @DarkFifiLaFume

Sorry the late reply. I don't have wavs that exactly represent each table, however I used  a mixture of the existing Adventure Kid waveforms from https://www.adventurekid.se/akrt/waveforms/adventure-kid-waveforms/, including some of my own generated using Matlab.

I can, with a bit of time, make a script that turns the "pre baked" tables in the code into WAVs
