### ISSUE TITLE
any more semi modular like stuff

### ISSUE THREAD

**Issue by modman2019** [ValleyAudio/ValleyRackFree#37]
Hi I really like Interzone.  Wondering if you can create something like the DFAM or mother 32 or neutron.

**Comment by ValleyAudio** [comment]
Hi @modman2019, I'm glad you like Interzone! At the moment I have no other semi modulars planned as I'm focusing on individual modules for now, as well as getting the current modules ready for v1.0. I will consider these designs in future plans though!

**Comment by modman2019** [comment]
Cool!
