### ISSUE TITLE
Rack v1: plugin.json updates required

### ISSUE THREAD

**Issue by cschol** [ValleyAudio/ValleyRackFree#38]
The manifest validation script found a few issues in your `plugin.json`:

```
Validating Valley
Interzone: invalid tags: SYNTH_VOICE
Amalgam: invalid tags: RING_MODULATOR
pluginUrl: no URL specified
```

Tags needs to adhere to the (case-insensitive!) tags defined in:
https://github.com/VCVRack/Rack/blob/v1/src/plugin.cpp#L534

`pluginUrl` can be set to README.md of the repository.

**Comment by ValleyAudio** [comment]
@cschol Fixed!
