### ISSUE TITLE
Plateau output high on restart

### ISSUE THREAD

**Issue by AlHeeley** [ValleyAudio/ValleyRackFree#39]
When I reopen a patch using a lot of Plateau wet signal I get really hloud distorted white noise that only goes away if I delete the module or turn wet signal to zero. Mostly it happens when I exit rack with a patch using Plateau (that's every one of mine...!) is running, then I reopen Rack a bit later, its as if all the plate reverb has been storing itself up for release as soon as Rack is running again. I tried replacing Plateau with another plate reverb (NYSTHI Plateverb) and I get no issue.

**Comment by AlHeeley** [comment]
[Omri's Entropia.vcv.zip](https://github.com/ValleyAudio/ValleyRackFree/files/3314910/Omri.s.Entropia.vcv.zip)

**Comment by AlHeeley** [comment]
here's another overdriven noise on startup 
[screeck.vcv.zip](https://github.com/ValleyAudio/ValleyRackFree/files/3315303/screeck.vcv.zip)

**Comment by millxing** [comment]
Yeah I'm getting the same problem on both my 2013 MacPro and 2019 MacBookPro. Come close to blowing out my speakers and my ears a couple of times. Platueau is definitely the issue.

**Comment by ValleyAudio** [comment]
@millxing Did you by any chance use mschack modules going into plateau?

**Comment by millxing** [comment]
Correctamundo! My default template uses a MSCHack mixer, with Plateau connected to the send/return. Do you know what's going on? I used the same combination countless times in 0.6 without issue. Thanks!

**Comment by ValleyAudio** [comment]
@millxing It's not plateau. It's an issue with the mixer. I'm assuming it's the unreleased v1 version? I tested it last night and what happens is that the mixer outputs a huge voltage when the patch starts. This then resonates through Plateau.

I've filed this issue with mschack.

**Comment by millxing** [comment]
ok thanks. You can see why I thought it was Plateau, but sorry for drawing the wrong conclusion.

**Comment by ValleyAudio** [comment]
@millxing No worries! A lot of people using that mixer reported the issue so it's kept me on my toes haha!
