### ISSUE TITLE
C++ style loop initial definitions cause compile error

### ISSUE THREAD

**Issue by Chaircrusher** [ValleyAudio/ValleyRackFree#4]
I'm trying this on Centos7 (basically RHEL7).  GCC 4.8.5.
I get this error: 
src/Topograph/patternGenerator.c:71:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (uint8_t i = 0; i < kNumParts; ++i) {
         ^

The fix is to turn on c99 mode.

diff --git a/Makefile b/Makefile
index 5875324..a1b3df6 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 
 # FLAGS will be passed to both the C and C++ compiler
 FLAGS +=
-CFLAGS += -O3
+CFLAGS += -O3 -std=c99
 CXXFLAGS += -O3
 
 # Careful about linking to libraries, since you can't assume much about the user's environment and library search path.

**Comment by ValleyAudio** [comment]
Thanks for the tip!
