### ISSUE TITLE
Interzone crackles when midi mapped

### ISSUE THREAD

**Issue by z-plane** [ValleyAudio/ValleyRackFree#40]
Just tried this and seems the params (cutoff, and env depth for me) get a bit of crackle when mapping using the VCV Midi-Map (using an Ableton Push controller). I'm currently trying to slow the parameters down by midi mapping via the TACT module (impromptu), but i can only do the cutoff... so far it seems to remove the crackle.

FYI, I tried this as wasn't sure if it was DSP load the might be causing this, but the patch is relatively small. leads me to think the parameters update too frequently when midi mapped?

ps. thanks for making your modules, they're great :)

**Comment by z-plane** [comment]
There's also a few more weird things happening with MIDI params not constraining to min/max and jumping from one end to the other (eg. Attack)

**Comment by ValleyAudio** [comment]
Hiya!

I've had a small look at the problem with my Korg Nanokontrol and I'm not experiencing the issues you described. There's no crackle and everything stays with range i.e 0-127 from my controller maps to 0 to 100%.
The control smoothing is done by Rack and not the plugin, so this issue might be a problem in Rack or with the MIDI-Map module itself.

I have a Livid Base controller at home which is very loosley like the Push, so I can report later if the issue occurs with that.

Few questions though:
- What OS are you on? 
- Have you updated to Rack v1.1 and updated the plugins?

**Comment by z-plane** [comment]
OSX 10.13.6
Rack v1.1 (just patching to 1.1.1 now), all plugins updated.

i suspect the wrapping issue is because the push has endless encoders...
