### ISSUE TITLE
Feature Request: Noise wavetable for Dexter

### ISSUE THREAD

**Issue by bgracie** [ValleyAudio/ValleyRackFree#45]
I would love a wavetable that crossfades between a sine wave and white noise.  You can achieve some really nice effects using a white noise mix as a modulation osc.

**Comment by ValleyAudio** [comment]
Hi @bgracie ! Yeah that's cool concept. The only thing though is that the noise would be pre-calculated and would cycle, so not random. Also my other problem is that I can't modify the Dexter wavetable "ROM" at the moment as it would potentially break other people's patches. In my upcoming Terrorform module you'll be able to import your own wavetables and try this out.

**Comment by bgracie** [comment]
Ah right, that makes sense re: not modifying the wavetable ROM.  I guess the different waves are locked to different positions of the dial.

That's really exciting about the new module!

Anyway thanks for your reply and for the plugin =)
