### ISSUE TITLE
Terrorform  : LPG activation button doesn't work

### ISSUE THREAD

**Issue by jsmonzani** [ValleyAudio/ValleyRackFree#48]
Hey,
Testing Terrorform from the freshly released version in the Library on Win10.
I can not click on the LPG button, I have to manually set it to, say 1 (by right-clicking on it) for it to become activated.
Furthermore, if I quit and relaunch Rack, the parameter is set to 0 again.

Thank you!

**Comment by ValleyAudio** [comment]
Did you hold it "on" for at least half a second? It says "Hold to Toggle" in the tool-tip

**Comment by jsmonzani** [comment]
Oh you're right! This works and resolves the issue. Sorry 👍
