### ISSUE TITLE
Use getVoltageSum() on Plateau audio inputs

### ISSUE THREAD

**Issue by MarcBoule** [ValleyAudio/ValleyRackFree#50]
Hi Dale,
I've been meaning to open this issue for a while, but just got to it now. I was wondering if you would consider using `getVoltageSum()` when reading the audio L and R inputs on Plateau. The module is justifiably not polyphonic, so in this case it would be nice to have that summing (it's also recommended in Rack's standards).
Thanks for all the great modules!
Cheers,
Marc

**Comment by RichieHindle** [comment]
+1 for this!  I've lost count of the number of times I've used Plateau with a polyphonic oscillator and been baffled that some of my notes don't sound.

**Comment by RichieHindle** [comment]
Works like a charm - many thanks!
