### ISSUE TITLE
Topograph: No external clock

### ISSUE THREAD

**Issue by 1xch** [ValleyAudio/ValleyRackFree#54]
I have the clock dial turned all the way left, it says 'Ext', but the module is not using the external clock.

External clock plugged in to the clock appears to have zero impact.

**Comment by ValleyAudio** [comment]
Did you toggle the "Run" switch?

**Comment by 1xch** [comment]
@ValleyAudio 
Yes, run switch toggled several times
It still reads Ext beneath , the clock dial number is at 37.68 and that appears to be the bpm its running at 
Expected behavior from my experience so far would be to plug in an external clock and have the unit register that immediately, but I am still new at all this.

Rack 1.1.6 on Linux Ubuntu (uncompiled  & release binary being run).

**Comment by ValleyAudio** [comment]
I haven't changed any code with Topograph. Please send me your patch so I can see what's going on.

**Comment by ValleyAudio** [comment]
@1xch Just tried the patch, uGraph seems to work just fine, although very slow. Is this the issue? It doesn't work via "Tap Tempo" or clock syncing.

Topograph expects a high speed clock for external clocking. The external clock should be 24, 8 or 4 pulse per quarter note (this is set in the right click menu). What this means is that there should be 24 clocks per beat. This is why it is so slow with a regular clock as seen in your patch. It's basically 24x slower than it should be.

A solution is to use Clocked by Impromptu. That lets you set the resolution on one of its 3 clock outputs.

**Comment by ValleyAudio** [comment]
@1xch Here is an example of Topograph / uGraph using Clocked.
[topographWithClocked.vcv.zip](https://github.com/ValleyAudio/ValleyRackFree/files/5357074/topographWithClocked.vcv.zip)

**Comment by 1xch** [comment]
okty
