### ISSUE TITLE
request:uGraph(topograph) Ignore tempo knob when external clock is patched

### ISSUE THREAD

**Issue by nnbveh** [ValleyAudio/ValleyRackFree#55]
I'm using randomize function in Rack quite often and it works wonders with topograph but it randomizes the tempo as well, which, in case of me using an external clock, messes the things up. Would it be possible to make so the tempo knob uncouples when external clock is plugged in?

As an alternative, when ext.clock plugged in, the knob could act as a clock divider or something, so we keep the things in sync with the rest of the patch but can get even more variety?

Thanks!

**Comment by ValleyAudio** [comment]
Good idea! I've coded this into Topograph and uGraph now, so it will be available soon in the next update.

**Comment by nnbveh** [comment]
FANTASTIC, thanks!
