### ISSUE TITLE
Terrorform: Problem with True FM setting when polyphony > 8

### ISSUE THREAD

**Issue by anlexmatos** [ValleyAudio/ValleyRackFree#56]
With 9 or more channels arriving at Terroform's V/Oct input, sometimes one or more channels of its output will become (nearly) silenced after the True setting is toggled. Once this has happened, when Rack is closed it will crash. Nothing of interest appears in Rack's log.txt.

The problem seems to occur most consistently when the polyphony is maxed at 16.

Running Rack 1.1.6 on Windows 7

**Comment by ValleyAudio** [comment]
Good spot! Looks like I made a severe typo in Terrorform. Fixed in source and will fixed when I push the next update ASAP.
