### ISSUE TITLE
Plateau Decay CV input not working

### ISSUE THREAD

**Issue by jon-joy-1999** [ValleyAudio/ValleyRackFree#57]
Trying to use the decay input to reduce overdrive on the output of Valley, but the decay input doesn't respond to the control signal sent to it.

**Comment by ValleyAudio** [comment]
I've just tested Plateau and the Decay responds to CV control as expected. Did you make sure to turn up the attenuator knob thats in-line with the Decay CV input?

**Comment by jon-joy-1999** [comment]
I could have sworn that I had turned that knob all the way up when I was trying to figure out why the control wasn't working. Maybe I had the CV plugged into the hole below the decay and was blind x(
