### ISSUE TITLE
Continuity improvement for tanhDriveSignal()

### ISSUE THREAD

**Issue by EleonoreMizo** [ValleyAudio/ValleyRackFree#58]
Hi, may I do a suggestion? I wanted to implement a Dattorro reverb and found out that you did one too with Plateau. I checked a bit the code and found `tanhDriveSignal()` in [NonLinear.hpp](https://github.com/ValleyAudio/ValleyRackFree/blob/v1.0/src/Common/DSP/NonLinear.hpp). It seems that the formula for |x| in the 0.75–1.3 range breaks the curve continuity at 0.75. I don’t know if it was intended or not. This is the red curve on [this graph](https://www.desmos.com/calculator/79crc5vibu). You could easily restore the continuity, along with the first derivative continuity by using `x * (2.5 - x) - 0.5625`, and lowering the other bound to 1.25.

**Comment by ValleyAudio** [comment]
Hey @EleonoreMizo , yes it looks like I made a slight mistake in my tanh approximation. I found that be narrowing the bounds for the linear region (y=x) to be between -0.7 to 0.7 this fixes the continuity. Thanks for spotting this error :)
