### ISSUE TITLE
Run trigger

### ISSUE THREAD

**Issue by NikolaiVChr** [ValleyAudio/ValleyRackFree#6]
The Topograph is one of my favorite modules in Rack, thanks for making it.

Any chance of CV controlled run?

**Comment by ValleyAudio** [comment]
You're welcome :)

Yeah this is planned for the next version.

**Comment by NikolaiVChr** [comment]
Great!

**Comment by bitfetcher** [comment]
I SO appreciate this module; great work!

I'm having trouble clocking it though. If I, for example, clock a trigger sequencer driving one drum and Topograph driving another, they just don't match. I use a button to simultaneously reset them, and I have the clock knob all the way down. I've even tested it against two trigger sequencers. They work lockstep, but Topograph seems to do its own thing. :(

**Comment by ValleyAudio** [comment]
Hi bitfetcher,

I suspect that the external  clock resolution of topograph isn't matched to what you're clocking with. By default topograph expects 24 pulses per quarter note, but this can be changed to either 8 or 4. This is changed in the right click menu. Maybe selecting a different resolution could fez your sync issue?

**Comment by ValleyAudio** [comment]
*fix

**Comment by bitfetcher** [comment]
Wow, thanks for the quick reply. And now I'm completely red-faced!

I re-opened the "test" file I had been using and everything is working just fine! I really don't know why I was getting a delayed pulse, but maybe I needed to restart Rack itself... I'm sorry to waste your time...

And if I have any more issues, I'll try to BPQN setting (thanks for that, I keep forgetting to check modules' options!) Or... I may put on a fez!! ;)

Thanks again for this amazing module!!

**Comment by ValleyAudio** [comment]
@NikolaiVChr I've implemented the run trigger that you requested :)

**Comment by NikolaiVChr** [comment]
Awesome, thank you. :)
