### ISSUE TITLE
No modules in browser after installing Valley 2.0.0

### ISSUE THREAD

**Issue by Motopomp** [ValleyAudio/ValleyRackFree#64]
No modules in browser after installing Valley 2.0.0, Osx10.10.5

![Capture d’écran 2021-12-01 à 11 46 21](https://user-images.githubusercontent.com/33150728/144220812-271467a5-8f0f-4c99-9a32-06f76b94ac5a.png)
![Capture d’écran 2021-12-01 à 11 49 55](https://user-images.githubusercontent.com/33150728/144221346-f623b68c-3d7c-4c97-808d-73ad3cc1e581.png)

**Comment by ValleyAudio** [comment]
Did you install the release I made on github? Because there is nothing submitted to the official library yet
