### ISSUE TITLE
plateau bypass not working also lots of resonance sound causing distortion

### ISSUE THREAD

**Issue by XtremeSounds** [ValleyAudio/ValleyRackFree#65]
HI I noticed the bypass is not working for plateau in V2. also it seems plateaus now causes a lot of distortion to the mix.  Sounds like resonance on a filter but I have resonance on my filter all the way down.  I am using the Vult Lateralus filter with some drive. maybe it is the problem there, but I was hearing this same sound using a different filter

**Comment by ValleyAudio** [comment]
@XtremeSounds Bypass has not been implemented yet. Also, regarding the resonance noise, would you be able to send me a copy of your patch please?

**Comment by XtremeSounds** [comment]
Sure here you go

**Comment by flydoggy** [comment]
The noise is caused by the input sensitivity.  The old default was -18db, but v2 is defaulting to 0db.  Changed the setting and distortion went away.

**Comment by XtremeSounds** [comment]
Thanks where is that located?

**Comment by flydoggy** [comment]
@XtremeSounds Right-click menu under input sensitivity

**Comment by XtremeSounds** [comment]
I think some sequencers are sending higher velocities  than others causing Plateau to vary in its output.  Compare SEQ3 with JW 8seq

**Comment by XtremeSounds** [comment]
are you aware the bypass still does not work?

**Comment by ValleyAudio** [comment]
Yeah, I was more focused on issues #66

**Comment by XtremeSounds** [comment]
this plateau is still heavily distorted after switching to -18 db on a patch I added it to. You can hear the distortion just increase like crazy and I have to turn my levels down. Using the default preset on Plateau and then switching to -18db. Sounds like static
