### ISSUE TITLE
some valley modules in rack pro vst cause crashes when reloading projects containing them.

### ISSUE THREAD

**Issue by offthesky** [ValleyAudio/ValleyRackFree#68]
steps to repro: load up amalgam, topograph, or dexter in rack pro vst. save ableton or reaper project. quit daw, reopen daw. reload project containing vst with either valley module listed above. daw crashes.

tested with: windows 10(latest build), 17" macbook pro (bootcamp) 8g ram, ableton 11(latest), reaper(latest), rack pro vst(latest)

note: wasn't able to test every valley module due to lack of time but... plateau and feline do not cause any crashes.

**Comment by ValleyAudio** [comment]
Related to #66
