### ISSUE TITLE
plateau sound is weaker in DAw

### ISSUE THREAD

**Issue by XtremeSounds** [ValleyAudio/ValleyRackFree#71]
HI I switched to Vcv rack pro and switching the audio output from my speakers to the DAW causes a noticeable decrease in sound lushness. If i turn up the volumes then it distorts. Not sure what is causing the difference here

**Comment by ValleyAudio** [comment]
This is the same as issue #67. I'm currently reverting back to the V1 DSP as I got too ambitious with a new and more efficient design which has lead to this issue.
