### ISSUE TITLE
Terrorform crashing VCV Rack 2 Pro VST in Renoise

### ISSUE THREAD

**Issue by dwat3r** [ValleyAudio/ValleyRackFree#72]
Hey, I'm experiencing issues with patches containing Terrorform.

The thing is that if I include one in a VST patch it's all good until I save and exit the DAW. Then when I'm trying to open the project, this error will pop up on open:
![image](https://user-images.githubusercontent.com/6506116/148700094-c65076d8-5907-48e9-a172-d7275cd7d298.png)

After that, when I remove the crashed plugin, this will pop up:
![vcv crash](https://user-images.githubusercontent.com/6506116/148700206-34c6070c-1ed4-4267-9e19-1a449ff59535.PNG)

This error is easily reproducible with a single, disconnected Terrorform in a Rack VST, with it's init patch.

The thing is that this problem is critical to me, since there's no other module which can stand up to the things what Terrorform can do. :)

**Comment by ValleyAudio** [comment]
Have you updated my modules to the latest version?

**Comment by dwat3r** [comment]
Thank you, yes I haven't noticed the update available, and yes it fixed my issue, many thanks!
