### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [ValleyAudio/ValleyRackFree#73]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?
Thanks!

**Comment by ValleyAudio** [comment]
The source code is covered by GPL-3.0, but the artwork is covered by copyright.

**Comment by falkTX** [comment]
Well sure, the code has copyright too. I am asking if there is a specific license for the artwork.
Is redistribution allowed? Any kind of modification or derivative works? Selling? Reuse in other works?

**Comment by ValleyAudio** [comment]
Yeah of course, so the closest to my philosophy is CC-BY-SA-4.0 (https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by falkTX** [comment]
That sounds great, could you make that any kind of official? Placing it in the readme, adding to the license file, or something like that.
Thanks a lot

**Comment by ValleyAudio** [comment]
Yeah I'll do that next. No worries!
