### ISSUE TITLE
uGrids

### ISSUE THREAD

**Issue by gbrandt1** [ValleyAudio/ValleyRackFree#8]
hi,
real muGrids have appeared:
https://www.modulargrid.net/e/other-unknown-%CE%BCgrids
if you don't mind, i'd like to make a mu-panel version based off Topograph for Rack?

**Comment by ValleyAudio** [comment]
Ooooh I was looking for mu grids the other day! I'm itching to make a compact eurorack myself. I could make a micro module for the next version :)

**Comment by gbrandt1** [comment]
ok cool :-)
