### ISSUE TITLE
Dexter load fail, missing symbol

### ISSUE THREAD

**Issue by davephillips** [ValleyAudio/ValleyRackFree#9]
Fedora 23 Linux
Rack 0.5.x

Hi Dale, thanks for the note re: Dexter ! It builds fine here but fails to load. Here's the error reported by Rack:

[warning] Failed to load library ./plugins/ValleyRackFree/plugin.so: ./plugins/ValleyRackFree/plugin.so: undefined symbol: _ZN12DexterWidgetC1Ev

Any suggestion for a fix ?

**Comment by ValleyAudio** [comment]
I'm away from keyboard right now. Someones had the same issue on Windows with the widget when pulling from my repo. This cleanly built and ran on my windows and Linux systems, and the releases are made on those.

I have a feeling that my source code may not have pushed correctly to git.

**Comment by davephillips** [comment]
Thanks, Dale. I'll check the binary as well.

**Comment by phdsg** [comment]
@ValleyAudio indeed a git transfer error: no sources for dexter:
look https://github.com/ValleyAudio/ValleyRackFree/tree/master/src

**Comment by ValleyAudio** [comment]
@phdsg Just seen haha. How embarrassing, knew it was a git push failure.

**Comment by ValleyAudio** [comment]
Try it now :)

**Comment by phdsg** [comment]
i think you somehow added the `Dexter` folder as a submodule. it's still empty when pulling. and i can't pull the submodule: `fatal: No url found for submodule path 'src/Dexter' in .gitmodules`

**Comment by davephillips** [comment]
Btw, the Linux binary for 0.5 works just fine. Beautiful work, Dale, very impressive. I'm a great lover of FM synthesis, I cut my synth programming teeth on Yamaha's TX81z back in the late 80s.

**Comment by ValleyAudio** [comment]
@phdsg Yep, found the .git file that was hidden there. Currently pushing the changes.

**Comment by ValleyAudio** [comment]
@davephillips Thanks very much :D The linux version was almost a no show because I called a function incorrectly. I love FM too. I have a DX7 with the SuperMax expansion installed. Seeing Akemie's Castle and Elektron's Digitone reignited my love for FM which naturally lead to the development of Dexter :)

**Comment by ValleyAudio** [comment]
@phdsg @davephillips Okay, the push is done.

**Comment by phdsg** [comment]
very nice. builds and loads and sounds. only tried a little bit. waiting for the 0.6 version to do real plays.

**Comment by davephillips** [comment]
Yep, it's all good here now. Looking forward to the 0.6 version too. Thanks again, Dale !
