### ISSUE TITLE
Debug output in InterpDelay.hpp?

### ISSUE THREAD

**Issue by cschol** [ValleyAudio/ValleyRackFree#92]
This causes spurious console output when Plateau is added to Rack:

```
src/dsp/delays/InterpDelay.hpp
68:            std::cout << newDelayTime << ", " << l << std::endl;
```

Can this be removed?

**Comment by ValleyAudio** [comment]
> This causes spurious console output when Plateau is added to Rack:
> 
> ```
> src/dsp/delays/InterpDelay.hpp
> 68:            std::cout << newDelayTime << ", " << l << std::endl;
> ```
> 
> Can this be removed?

Oh my, sorry about that. Yes, I will remove it and push a new commit.

**Comment by ValleyAudio** [comment]
This has been fixed, I will now comment with the new hash on my issue thread

**Comment by cschol** [comment]
Thank you!
