### ISSUE TITLE
Dexter, Operators 3 and 4

### ISSUE THREAD

**Issue by takyano** [ValleyAudio/ValleyRackFree#94]
I am having some issues with the behavior of the Level, Coarse and Fine controls in Dexter.
I am running into algorithms where:

- the Operator Coarse and Fine controls don't seem to do anything.
- the Operator 4 Level control doesn't seem to work.
VCV Rack 2.4.1
Windows 10

### Algorithm 13
2 -> 1 -> A
4 -> 3 -> B

The outputs are swapped.
4 -> 3 -> A
2 -> 1 -> B

OP 4 Level control do not work
Global Feedback works.

Operator Coarse and Fine have no effect on OP 3 and OP 4
Global Voice A Coarse and Fine affect all Operators.

### Algorithm 14
3 -> 2 -> 1 -> A
4 -> B

The outputs are not swapped.

OP 4 Level control works
Global Feedback works.

At first I thought it was:

Operator Coarse and Fine for OP 2 and OP 3 have no effect.
Global Voice A Coarse and Fine affect OP 1, OP 2 and OP 3.
But it appears that the final modulated OP 1 is not getting to Voice A.
Checking OP 1 shows that the Coarse and Fine for OP 2 and OP 3 do work.

### Algorithm 16
4 -> A
3 -> 2 -> 1 -> B

OP 4 Level control works
Global Feedback works.

Operator Coarse and Fine for OP 4 go to OP 4 direct output but not Voice A
Global Voice A Coarse and Fine do not go to OP 4 direct output, but do affect Voice A.
Global Voice B Coarse and Fine do go to OP 4 direct output, but do not affect Voice A.

OP 2 and OP 3 Level controls do not work
OP 3 Level does modulate 2
OP 2 Level does not modulate 1
Or the Level control has no effect.

**Comment by ValleyAudio** [comment]
Hi @takyano, thanks for spotting these issues for me. Looks like I had overlooked the algorithm implementations that were otherwise overhauled for v2.4. I've made the fixes, and I am now about to submit the update to the VCV Rack Library team.

**Comment by takyano** [comment]
More testing with 2.4.3

Algorithms 14 and 16 both have an arrangement of 3 -> 2 -> 1  and 4 into separate A and B

### Algorithm 14
3 -> 2 -> 1 -> A
4 -> B

I am finding:
Global Voice A Oct, Coarse and Fine:
- do affect A output.
- do not affect OP 1, OP 2 or OP 3.

Global Voice B Oct, Coarse and Fine:
- do  affect voice B output
- do affect OP 4
- do affect OP 1, OP 2 or OP 3


### Algorithm 16
4 -> A
3 -> 2 -> 1 -> B

Global Voice A Oct, Coarse and Fine:
- do affect Voice A
- do not affect OP 4

Global Voice B Oct, Coarse and Fine:
- do affect Voice B
- do affect OP 1, OP 2, OP 3
- do affect OP 4


I haven't been through all the Algorithms so this feels like Whack-A-Mole, but I found these:

### Algorithm 13
2 -> 1 -> A
4 -> 3 -> B

Global Voice A Oct, Coarse and Fine:
- affect Voice A
- do not affect OP 1 and OP 2

Global Voice B Oct, Coarse and Fine:
- affect Voice B
- affect OP 3 and OP 4
- affect OP 1 and OP 2


### Algorithm 15
Voice A seems to be OP 3 only, ignoring OP 2 and OP 4

**Comment by takyano** [comment]
Do you want a new ticket for issues for 2.4.3?

**Comment by ValleyAudio** [comment]
I've reopened it. I'll look at this as soon as I can.
