### ISSUE TITLE
Dexter V/oct input is 0.1 at max but should be 1.0

### ISSUE THREAD

**Issue by Petervos2018** [ValleyAudio/ValleyRackFree#95]
Hi Dale,

Edit 3rd november 2023 : using the V/Oct A and B work as expected, but I still can’t change the whole range of Algos via CV. (and it’s not backward compatible with V 1)

I am talking about the CV inputs, they are all 1/10 of the old (V1) range, they should be going to 1 instead of 0.1 max.

![afbeelding](https://github.com/ValleyAudio/ValleyRackFree/assets/46076474/f39e2185-74a2-490a-9261-ad713e661e12)

When I play an octave it only gives me 1/10 of a scale, when I multiply the cv by ten it works as expected.

See also

https://community.vcvrack.com/t/looking-for-valley-dexter-presets/20847/10?u=yeager

![afbeelding](https://github.com/ValleyAudio/ValleyRackFree/assets/46076474/407a9676-625b-43a4-ad58-dffa3f280f12)

All these go from 0 to +-0.1 but should go from 0 to +-1.0

And the assignable mods 1 to 4 go from 0 to +-1.0 but the range is only +-0.5 at max (but this was also the case in V1 so better to not change this for backwards-compatibility ) 

In V1 you had

https://github.com/ValleyAudio/ValleyRackFree/blob/6b0f6e39b2a544b11eade58bab93a588275ee36d/src/Dexter/Dexter.cpp#L67

In V2 you have

https://github.com/ValleyAudio/ValleyRackFree/blob/9a43da65e74c08a7b113135498329e083fd0c16c/src/Dexter/Dexter.cpp#L67

Somewhere you went from 1.0 to 0.1

Greetings Peter

Also the ago parameter is wrong it only gives me 3 of the available 23 alos

![afbeelding](https://github.com/ValleyAudio/ValleyRackFree/assets/46076474/366b3255-addd-44c8-826c-d15aed98bd87)

If you feel this is a nonsense post please close it.

**Comment by ValleyAudio** [comment]
Thanks for spotting that! Fixed in upcoming version 2.4.5
